# Generated by Django 5.2.1 on 2025-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location_link',
            field=models.URLField(blank=True, help_text='e.g.: https://goo.gl/maps/...', max_length=500, null=True, verbose_name='Google Maps Link'),
        ),
    ]
